// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2nLhRUjNb2Z3dHauIqipQUXzhVRvFxZ0',
    appId: '1:108066114328:web:14059dfe55a153630b2c6d',
    messagingSenderId: '108066114328',
    projectId: 'bastion23-m2',
    authDomain: 'bastion23-m2.firebaseapp.com',
    storageBucket: 'bastion23-m2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLqE27DmU7fn7okV0t7hnK9hk8czPtJe4',
    appId: '1:108066114328:android:9a6f142e4e4dbbee0b2c6d',
    messagingSenderId: '108066114328',
    projectId: 'bastion23-m2',
    storageBucket: 'bastion23-m2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGsn90u9ysp663XIw6Td4HL5ET-lpCJag',
    appId: '1:108066114328:ios:e2b9796fbeb618f10b2c6d',
    messagingSenderId: '108066114328',
    projectId: 'bastion23-m2',
    storageBucket: 'bastion23-m2.appspot.com',
    iosBundleId: 'com.example.bastion23',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGsn90u9ysp663XIw6Td4HL5ET-lpCJag',
    appId: '1:108066114328:ios:d02a2b08dc0cc36d0b2c6d',
    messagingSenderId: '108066114328',
    projectId: 'bastion23-m2',
    storageBucket: 'bastion23-m2.appspot.com',
    iosBundleId: 'com.example.bastion23.RunnerTests',
  );
}
